version: "3.9"
   
services:
  db:
    image: postgres
    env_file:
      - backend/.envs/local/.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    container_name: aisle_optimizer
    build:
      context: ./backend
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    volumes:
      - staticfiles:/backend/staticfiles
      - ./backend:/backend
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - staticfiles:/staticfiles
      - ./frontend:/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  pgdata_volume:
  staticfiles:
  frontend:
  backend:
