name: Run Black
on: pull_request
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install black==24.1.0
      - run: |
          black --check --verbose backend/api backend/apps